spring:
  application:
    name: gigsync

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD}
    mongodb:
      uri: ${MONGO_URL}
      database: gigsync-chat
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY}" password="${KAFKA_API_SECRET}";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY}" password="${KAFKA_API_SECRET}";

server:
  error:
    include-message: always
  tomcat:
    max-http-post-size: 500MB

resend:
  api-key: ${RESEND_API_KEY}

app:
  email:
    sender: ${APP_SENDER_EMAIL}

jwt:
  access-token:
    expiration-time: ${JWT_ACCESS_EXP}
  refresh-token:
    expiration-time: ${JWT_REFRESH_EXP}
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}
    s3:
      bucketName: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: 'false'

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "https://gigsync-fe.vercel.app"